### ISSUE TITLE
you stole my cheats and didnt credit me

### ISSUE THREAD

**Issue by FieriFerret** [twoheadidduck/Subrosa-Cheats#1]
same as title

**Comment by twoheadidduck** [comment]
Never stole it. Just uploaded it for everyone to use you retard

**Comment by FieriFerret** [comment]
you claimed that you "leaked" them which logically means you stole them and reuploaded them
which tbf i dont really care i'm just wondering why no credit 😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠

**Comment by twoheadidduck** [comment]
Why do you even care
